[package]
name = "stalos_v0_3"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres", "r2d2", "serde_json"] }
actix-web = "4.9.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
